services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_DB: ${JDBC_DATABASE_NAME}

    ports:
      - 5432:5432

  rabbit:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  db_test:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: Test
    ports:
      - 5433:5432
